/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [column1]
      ,[length_url]
      ,[length_hostname]
      ,[ip]
      ,[nb_dots]
      ,[nb_hyphens]
      ,[nb_at]
      ,[nb_qm]
      ,[nb_and]
      ,[nb_or]
      ,[nb_eq]
      ,[nb_underscore]
      ,[nb_tilde]
      ,[nb_percent]
      ,[nb_slash]
      ,[nb_star]
      ,[nb_colon]
      ,[nb_comma]
      ,[nb_semicolumn]
      ,[nb_dollar]
      ,[nb_space]
      ,[nb_www]
      ,[nb_com]
      ,[nb_dslash]
      ,[http_in_path]
      ,[https_token]
      ,[ratio_digits_url]
      ,[ratio_digits_host]
      ,[punycode]
  FROM [PhishingDatabase].[dbo].[Phishing_Dataset_Cleaned]